POST http://localhost:3000/users
content-Type: application/json

{
    "username": "esgiraldop",
    "email": "erick@giraldo.com",
    "password": "password123"
}

###
GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks?id=1
Accept: application/json

###
GET http://localhost:3000/tasks/1
Accept: application/json

###
GET http://localhost:3000/users?id=3

###
GET http://localhost:3000/users?email=nico@picon.com

###
DELETE http://localhost:3000/tasks?id=1
Content-Type: application/json

{

}
###
PUT http://localhost:3000/users/25b3
Content-Type: application/json

{
    "username": "nicopicon",
    "email": "nico@picon.com",
    "password": "password123"
}

###
PATCH http://localhost:3000/tasks/1
Content-Type: application/json

{
    "active": false
}

###
GET http://localhost:3000/users/1?_embed=tasks